version: "3"

services:
  backend:
    image: citybikes-backend
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - backend
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresDb:/data/postgres
    networks:
      - backend
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=postgresDatabase
volumes:
  postgresDb:
networks:
  backend:
    driver: bridge
