version: "3"

services:
  backend:
    image: citybikes-backend
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresDb:/data/postgres
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=postgres-database
      - DATABASE_URL="postgresql://dev:passwd@postgres:5432/postgres-database?schema=public"
volumes:
  postgresDb:
